# Generated by Django 6.0.6 on 2026-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='task_completed',
            new_name='tasks_completed',
        ),
    ]
